### ISSUE TITLE
Add `#[optfield(skip)]`?

### ISSUE THREAD

**Issue by dnaaun** [roignpar/optfield#12]
Is there interest in adding something like:

```rust
#[optfield(UserChanges)]
struct User {
  #[optfield(skip)]
  id: i64,
  first_name: String,
  last_name: String
}
```

Which would generate:

```rust
struct UserChanges {
  id: i64,
  first_name: Option<String>,
  last_name: Option<String>
}
```

The use case that motivates this features for me is actually the one in the example: generating a struct representing changes to a row in a db (but I would like the `id` field not to be optional in the `*Changes` struct).

Serde has [something like this](https://serde.rs/field-attrs.html#skip), btw.

-----

I do have to say: I was about to write a macro to duplicate this whole crate, and then I thought "why don't I google to check if this exists", and I was so relieved to find out it exists! Thank you!

**Comment by dnaaun** [comment]
I'd be happy to put up a PR btw.

**Comment by dnaaun** [comment]
It looks like the syntax will have to be:

```rust
#[optfield(UserChanges, skip=(id,)]
struct User {
   // ...
}
```

If we're going to avoid converting the whole thing to a derive macro.

**Comment by roignpar** [comment]
Hi @dnaaun, thank you for the suggestion.
`optfield` was not built with per-field configuration in mind and this seems to cause various annoyances as discussed in other issues and PRs.
Fortunately there is another crate that already offers similar functionality as well as what you are asking.
As exemplified at point 4 in the features list, [OptionalStruct](https://github.com/lesurp/OptionalStruct) already has what you are looking for: `#[optional_skip_wrap]`.
`optfield` is pretty much complete as is and will most probably not implement any new features, only bug fixes.

**Comment by dnaaun** [comment]
Thank you very much for your reply!
