### ISSUE TITLE
Detect and resolve duplicate field attributes when adding to existing struct

### ISSUE THREAD

**Issue by BTOdell** [roignpar/optfield#7]
Example:
```rust
#[optfield(
    pub ModifySinkJson,
    attrs,
    field_attrs = add(
        serde(default, skip_serializing_if = "Option::is_none")
    ),
    merge_fn = pub merge
)]
#[derive(Serialize, Deserialize)]
pub struct SinkJson {
    #[serde(rename = "type")]
    pub type_: String,
    pub address: String,
    #[serde(default)]
    pub filter: Vec<u32>,
    #[serde(flatten)]
    pub args: Map<String, Value>,
}
```

My `SinkJson` type already uses `#[serde(default)]` in the base struct. But when `optfield` adds the second `serde(default)` field attribute, it generates a compile error:
```
error: duplicate serde attribute `default`
  --> src\config\sink.rs:14:15
   |
14 |         serde(default, skip_serializing_if = "Option::is_none")
   |               ^^^^^^^
```

I can imagine implementing a feature like this may be difficult to do in the world of Rust macros, but would be really nice if it could be done.

**Comment by roignpar** [comment]
Thank you for pointing this out.
Indeed, this requires more attention and work than I currently have available for this project.
Feel free to open a PR or share any workarounds that you find.
